### ISSUE TITLE
Can you give a step-by-step example for you to use this module?

### ISSUE THREAD

**Issue by dbernstein** [SumoLogic/sumo-collector-puppet-module#1]
I've already got a puppet module that I'm firing up using puppet-librarian.   

I tried to pull this in directly from git using puppet librarian.  That didn't work.  Next I tried to reference it in my puppet module's manifest/site.pp using the directive: 
include sumologic::sumo

after having cloned the repo to /etc/puppet/modules_dist/sumologic and copied my config files here: 
/etc/puppet/files/sumo/sumo.conf
/etc/puppet/files/sumo/sumo.json

modules_dist is in the modulepath set in my modules puppet.conf.

I didn't see any complaints in the cloud-init-ouput.log.  But sumologic did not get installed.  

Anyway, a step by step guide to using this module would be helpful.

**Comment by duchatran** [comment]
@eugk : could you help out with this issue?

**Comment by tparnell8** [comment]
sure... I can probably put one together.

I think the simple answer is that the module is in a subdirectory in this repo, and thus that subdirectory needs to be in the module path.

IIRC modules need to sit in `modules/` so in this case the module should sit in `modules/sumo` but if you clone this repo the sumologic module will sit in `modules/sumo-collector-puppet-module/sumo` which would be invalid unless you also add that module path to your modules. 

Also you have to atleast include the module in your puppet files.

**Comment by tparnell8** [comment]
@dbernstein so I am def getting to this, before I write much more I'd like to see #10 merged in as it fixes a currently broken feature.

**Comment by duchatran** [comment]
@tparnell8: Tommy, I merged that one. Let me know if you need something else.

**Comment by arunpatyal** [comment]
@dbernstein: The repository needs to be cloned in the modules directory of puppet and renamed to sumo. The information has been added to readme. Let me know if any additional information is needed. Closing the issue.
