### ISSUE TITLE
sumo_json_source_path not defined in nix_config.pp

### ISSUE THREAD

**Issue by adamcousins** [SumoLogic/sumo-collector-puppet-module#18]
Hi There,

From what i can tell, nix_config.pp is missing a value defined for sumo_json_source_path variable.

To fix this in my local i have included inherits sumo::params in nix_config.pp

Is this a bug or am i missing something?
Cheers
Adam

**Comment by drewrothstein** [comment]
Ran into the same bug, here is a [PR](https://github.com/SumoLogic/sumo-collector-puppet-module/pull/19).

**Comment by arunpatyal** [comment]
The [PR](https://github.com/SumoLogic/sumo-collector-puppet-module/pull/19) was merged. The latest update has changes which makes this issue as not applicable.
