### ISSUE TITLE
support /usr/local/SumoCollector installs

### ISSUE THREAD

**Issue by jdavisp3** [SumoLogic/sumo-collector-puppet-module#22]
Sometimes the collector seems to install itself in `/usr/local` instead of `/opt`. This means the puppet manifest does not recognize that the collector has been installed and thus will run the executable for each puppet run.

**Comment by jdavisp3** [comment]
Any feedback here? Installs that go into `/usr/local` also seem somewhat broken and don't seem to install the upstart service configuration. This is on AWS EC2 on an Ubuntu 14 image. Any useful information I can provide here?

**Comment by arunpatyal** [comment]
The installation by default goes to /opt. In no case it should go to /usr/local. The /usr/local/sumo directory is used for downloading the installation package and other required files (sources.json etc.) 
The module has been updated, can you test and verify if you still see the issue?

**Comment by arunpatyal** [comment]
Please create a new issue, if the problem is reproduced.
