### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mattk42** [SumoLogic/sumo-collector-puppet-module#27]
It looks like there are release tags, the latest of which was created about a year ago. The latest changes committed to the master branch are 5 months old and are not in any release. Is this puppet module still being maintained and supported by SumoLogic?

**Comment by arunpatyal** [comment]
The latest release of the module has been created, it contains latest changes + new changes to support the current version of collector. Please check: https://github.com/SumoLogic/sumo-collector-puppet-module/releases/tag/0.2.0
