### ISSUE TITLE
Does not appear to support later versions of Sum collector

### ISSUE THREAD

**Issue by jsilverman-blispay** [SumoLogic/sumo-collector-puppet-module#28]
There were some changes after version 19.137 of the Sumo Logic collection agent that seem to be unsupported by this Puppet module. Most notably, the _user.properties_ file replaces sumo.conf

Is this Puppet module still actively developed? will it work for the newest Sumo Logic collector?

**Comment by arunpatyal** [comment]
The module has been updated to support latest version of Sumo collector. Please review and let me know if you face any issues.
