### ISSUE TITLE
PR 32 breaks compatibility with older versions of puppet

### ISSUE THREAD

**Issue by machad** [SumoLogic/sumo-collector-puppet-module#34]
Pull request 32 merges in data type declarations that are incompatible with old versions of puppet. Some environments are unable to use the latest and greatest versions of puppet, rendering the master branch broken for them (us).

**Comment by arunpatyal** [comment]
@machad Please share the version of Puppet you have installed?

**Comment by machad** [comment]
@arunpatyal Version 3.8.7.

**Comment by arunpatyal** [comment]
@machad Is it ok for you to continue using the older version using the release tag: v0.1.7? https://github.com/SumoLogic/sumo-collector-puppet-module/tree/v0.1.7

**Comment by arunpatyal** [comment]
@machad I am reviewing v0.1.6. Do you have any specific issues or functionalities which should be supported by the module?

**Comment by arunpatyal** [comment]
@machad Module back-ported to support puppet 3.8.7. I am closing the issue. Please open a new issue if you have any questions/issues.
